<a href="https://colab.research.google.com/github/ggmmi1/class25-1/blob/main/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip3 install torch torchvision torchaudio

In [7]:
import torch
import numpy as np
torch.__version__

'2.5.1+cu121'

### 1-1. 초기화 되지 않은 Tensor
-특정한 값이 채워지지 않은 상태로 생성되는것

In [8]:
tensor = torch.empty(4,2)
print(tensor)

tensor([[1.7268e-19, 4.5078e-41],
        [1.7268e-19, 4.5078e-41],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


### 1-2. 상수로 초기화 된 Tensor
- 'torch.zeros()'
- 'torch.ones()'

In [17]:
a = torch.ones(3,4, dtype=torch.long) #dtype = 데이터 타입 지정
b = torch.zeros(2,2)

print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1-3. 무작위하게 초기화된 Tensor
='torch.rand: 0~1 사이의 값으로 무작위 초기화
- 'torch.randn: 표준정규분포에서 무작위 초기화

In [19]:
a = torch.rand(3,3)
b = torch.randn(3,3)
print(a,b)

tensor([[0.1721, 0.3214, 0.4254],
        [0.8941, 0.5485, 0.2627],
        [0.6346, 0.0967, 0.9055]]) tensor([[-0.2778,  2.0816, -1.3949],
        [-0.6792, -1.6449, -0.3560],
        [-2.2427, -0.7588,  3.5368]])


### 1-4. 직접 입력한 값으로 초기화

In [21]:
a = torch.tensor([1, 2.3])
a

tensor([1.0000, 2.3000])


### 1-5. Numpy 배열로부터 초기화

In [25]:
nd_arr = np.array([1,2,3])

a = torch.from_numpy(nd_arr)

#numpy array로 변환
b = torch.tensor([1, 2.3])
new_nd = b.numpy()
type(new_nd)

numpy.ndarray

In [27]:

nd_arr = np.array([1,2,3])

a = torch.from_numpy(nd_arr)
b = torch.tensor([1, 2, 3, 4, 5])
new_nd = b.numpy()
new_nd[2] = 100 # new_nd[2]가 100으로 수정
print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])


### 1-6. 특정 텐서와 같은 사이즈, 무작위로 값을 채움

In [26]:
a = torch.ones(3,4, dtype=torch.long)
b = torch.rand_like(a, dtype=torch.float)  #randn_like, 정규분포로 바뀜 zeros_like,0으로 바뀜
b

tensor([[0.3761, 0.6184, 0.6829, 0.9360],
        [0.1529, 0.5430, 0.5535, 0.0284],
        [0.0541, 0.7700, 0.8875, 0.8602]])

 ## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [44]:
a = torch.empty(3,4)
print(a)

tensor([[ 1.9745e+26,  3.1703e-41,  3.3824e-33,  3.9600e+16],
        [ 1.1495e-24,  4.5078e-41,  7.5605e-03,  4.5077e-41],
        [ 1.1308e-30, -5.2160e-17,  9.2785e+04,  4.5077e-41]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [43]:
a = torch.zeros((2, 5, 3), dtype=torch.float64)

print(a)



tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [42]:
a = torch.ones((4, 4), dtype=torch.int)  #int:int32, short:int16, long:int64

print(a)



tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [46]:
a = torch.rand(3,3)
a

tensor([[0.3258, 0.1474, 0.2626],
        [0.7544, 0.7519, 0.8796],
        [0.1156, 0.0191, 0.5450]])

### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [47]:
a= torch.tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요.

In [51]:
a = torch.randn(2,2)
print(a)
result = torch.zeros_like(a)
print(result)

tensor([[ 0.5731, -0.8149],
        [ 1.7952,  0.9084]])
tensor([[0., 0.],
        [0., 0.]])


### 1-7. Tensor의 속성

In [55]:
divice = torch.device("cuda" if torch.cuda.is_available()else "cpu")
tensor = torch.rand(3,4, dtype = torch.float64)


print(tensor.size()) #사이즈
print(tensor.shape)  #사이즈
print(tensor.dtype) #데이터 타입
print(tensor.device) #디바이스

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


### 1-8. 특정 타입의 Tensor 생성


In [57]:
tensor = torch.rand(3,4, dtype = torch.float64)

float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.dtype)

int_tensor = torch.IntTensor([1.1, 2.3, 3.4])
print(int_tensor)
print(int_tensor.dtype)

torch.float32
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


###1-9. 데이터 타입 캐스팅

In [58]:
float_tensor = torch.FloatTensor([1, 2, 3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1, 2, 3])
print(float_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [65]:
tensor = torch.rand(3,4, dtype = torch.float64)
device = torch.device("cuda" if torch.cuda.is_available()else "cpu")
tensor = tensor.to(device)
tensor.device




device(type='cuda', index=0)

### 1-11. 다차원 Tensor 표현

#### 1-11-0. 0D Tensor(Scalar)
-하나의 값을 담고 있는 텐서

In [66]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


#### 1-11-1. 1D Tensor(Vector)
-값들을 저장하고 있는 리스트와 유사한 텐서

In [67]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-2. 2D Tensor(Matrix)
-행렬과 같은 모양으로 두개의 축이 존재

In [69]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


#### 1-11-3. 3D Tensor(Cube)
-큐브와 같은 형태로 세개의 축이 존재

In [71]:
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]],
                  [[1,2,3], [4,5,6], [7,8,9]],
                  [[1,2,3], [4,5,6], [7,8,9]]
                  ])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


#### 1-11-4. 4D Tensor
-4개의 축

In [73]:
t4 = torch.rand(3,2,4,5)
t4

tensor([[[[0.2535, 0.7310, 0.1717, 0.0036, 0.1429],
          [0.3557, 0.2756, 0.7998, 0.2807, 0.3255],
          [0.3935, 0.0577, 0.3324, 0.3061, 0.3763],
          [0.6478, 0.3439, 0.5702, 0.4083, 0.7174]],

         [[0.6656, 0.8504, 0.3073, 0.8378, 0.4381],
          [0.0119, 0.9920, 0.9380, 0.5964, 0.9224],
          [0.0138, 0.8655, 0.2361, 0.6287, 0.7315],
          [0.6143, 0.0126, 0.9810, 0.7511, 0.1092]]],


        [[[0.2766, 0.2365, 0.6339, 0.4964, 0.9438],
          [0.0355, 0.7726, 0.5427, 0.9471, 0.7830],
          [0.6583, 0.4894, 0.5508, 0.3117, 0.4611],
          [0.0197, 0.0519, 0.5392, 0.0732, 0.0631]],

         [[0.8341, 0.5589, 0.5308, 0.0295, 0.9177],
          [0.2104, 0.1169, 0.7518, 0.0566, 0.1542],
          [0.1346, 0.9097, 0.0458, 0.5856, 0.5497],
          [0.1666, 0.7803, 0.1802, 0.6875, 0.8917]]],


        [[[0.6815, 0.9345, 0.1984, 0.9259, 0.3636],
          [0.9953, 0.4759, 0.3284, 0.7846, 0.9030],
          [0.2541, 0.2263, 0.6578, 0.8381, 0.6753],
