<a href="https://colab.research.google.com/github/ggmmi1/class25-1/blob/main/02_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 02. Tensor의 연산


In [ ]:
import torch

### 2-1. 산술 연산

In [ ]:
tensor = torch.rand(2,2)
print(tensor)
tensor = tensor * 2
print(tensor)
tensor = tensor + 1

tensor([[0.6749, 0.1682],
        [0.5041, 0.5569]])
tensor([[1.3498, 0.3364],
        [1.0082, 1.1138]])


In [ ]:
#1 더하기
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x,y)
print(x+y)

tensor([[0.3335, 0.6209],
        [0.3201, 0.1787]]) tensor([[0.3768, 0.9303],
        [0.4769, 0.5047]])
tensor([[0.7104, 1.5513],
        [0.7970, 0.6835]])


In [ ]:
#2
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x,y)
print(x+y)
print(add)

tensor([[0.1531, 0.8223],
        [0.0150, 0.4885]]) tensor([[0.4718, 0.2869],
        [0.4905, 0.2303]])
tensor([[0.6249, 1.1092],
        [0.5055, 0.7188]])
tensor([[0.6249, 1.1092],
        [0.5055, 0.7188]])


In [ ]:
# in - place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x)  #더하기 한 결과를 y에 덮어 씌움
print(y)

tensor([[0.7780, 1.9315],
        [0.5206, 1.2073]])
tensor([[0.7780, 1.9315],
        [0.5206, 1.2073]])


In [ ]:
#빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub)


tensor([[ 0.2393, -0.3257],
        [-0.2008,  0.0585]])
tensor([[ 0.2393, -0.3257],
        [-0.2008,  0.0585]])


In [ ]:
#곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul)


tensor([[0.0173, 0.2029],
        [0.1268, 0.2068]])
tensor([[0.0173, 0.2029],
        [0.1268, 0.2068]])


In [ ]:
#나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x/y)
print(div)


tensor([[0.0163, 0.4965],
        [0.9707, 0.5871]])
tensor([[0.0163, 0.4965],
        [0.9707, 0.5871]])
