<a href="https://colab.research.google.com/github/ggmmi1/class25-1/blob/main/02_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 02. Tensor의 연산


In [ ]:
import torch

### 2-1. 산술 연산

In [ ]:
tensor = torch.rand(2,2)
print(tensor)
tensor = tensor * 2
print(tensor)
tensor = tensor + 1

tensor([[0.6749, 0.1682],
        [0.5041, 0.5569]])
tensor([[1.3498, 0.3364],
        [1.0082, 1.1138]])


In [ ]:
#1 더하기
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x,y)
print(x+y)

tensor([[0.3335, 0.6209],
        [0.3201, 0.1787]]) tensor([[0.3768, 0.9303],
        [0.4769, 0.5047]])
tensor([[0.7104, 1.5513],
        [0.7970, 0.6835]])


In [ ]:
#2
x = torch.rand(2,2)
y = torch.rand(2,2)
add = torch.add(x,y)
print(x,y)
print(x+y)
print(add)

tensor([[0.1531, 0.8223],
        [0.0150, 0.4885]]) tensor([[0.4718, 0.2869],
        [0.4905, 0.2303]])
tensor([[0.6249, 1.1092],
        [0.5055, 0.7188]])
tensor([[0.6249, 1.1092],
        [0.5055, 0.7188]])


In [ ]:
# in - place 바꿔치기 연산
add = torch.add(x,y)
print(add)
y.add_(x)  #더하기 한 결과를 y에 덮어 씌움
print(y)

tensor([[0.7780, 1.9315],
        [0.5206, 1.2073]])
tensor([[0.7780, 1.9315],
        [0.5206, 1.2073]])


In [ ]:
#빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub)


tensor([[ 0.2393, -0.3257],
        [-0.2008,  0.0585]])
tensor([[ 0.2393, -0.3257],
        [-0.2008,  0.0585]])


In [ ]:
#곱하기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul)


tensor([[0.0173, 0.2029],
        [0.1268, 0.2068]])
tensor([[0.0173, 0.2029],
        [0.1268, 0.2068]])


In [ ]:
#나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div = torch.div(x,y)
print(x/y)
print(div)


tensor([[0.0163, 0.4965],
        [0.9707, 0.5871]])
tensor([[0.0163, 0.4965],
        [0.9707, 0.5871]])


### 2-2 각종연산

In [ ]:
a = torch.tensor(-10)
print("절대값", torch.abs(a))

b = torch.tensor(3.3)
print("올림", torch.ceil(b))
print("반올림", torch.ceil(b))
print("내림", torch.ceil(b))


c = torch.rand(2,2)
print("클램프", torch.clamp(c, -0.5, 0.5))

#c다른 방법
c_1 = torch.tensor([[0.8, 0.3], [0.7, 0.5]])
print("클램프", torch.clamp(c_1, -0.5, 0.5))

절대값 tensor(10)
올림 tensor(4.)
반올림 tensor(4.)
내림 tensor(4.)
클램프 tensor([[0.0867, 0.2381],
        [0.4623, 0.1989]])
클램프 tensor([[0.5000, 0.3000],
        [0.5000, 0.5000]])


In [ ]:
x = torch.randn(2,2)
y = torch.tensor([[1,2], [3,4]])
print("최소값", torch.min(x))
print("최대값", torch.max(x))
print("평균", torch.mean(x))
print("표준편차", torch.std(x))

print("모든 원소의 합", torch.sum(y))
print("모든 원소의 합", torch.sum(y, dim=1))
print("모든 원소의 곱", torch.prod(y))
print("중복된 값 제거", torch.unique(torch.tensor([1,1,2,2,2,3,3,3,3,4,4,4,4])))

최소값 tensor(0.0451)
최대값 tensor(1.0814)
평균 tensor(0.4460)
표준편차 tensor(0.4946)
모든 원소의 합 tensor(10)
모든 원소의 합 tensor([3, 7])
모든 원소의 곱 tensor(24)
중복된 값 제거 tensor([1, 2, 3, 4])


### 2-3. 내적(dot product)

In [ ]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])

result = torch.matmul(x,y)
print(result)

tensor([[19, 22],
        [43, 50]])


## PyTorch Quiz 2 : 연산

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.

In [ ]:
a = torch.tensor([2,4,6])
print(a)
print(a+5)
print(a-3)

tensor([2, 4, 6])
tensor([ 7,  9, 11])
tensor([-1,  1,  3])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [ ]:
a =torch.rand(3,3)
b = torch.rand(3,3)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[1.1692, 0.2045, 1.3219],
        [1.2159, 1.3505, 1.2624],
        [1.1898, 1.3787, 0.5348]])
tensor([[ 0.3852, -0.0713, -0.2280],
        [ 0.3832, -0.2745,  0.2080],
        [ 0.3001, -0.3786,  0.2025]])
tensor([[0.3047, 0.0092, 0.4239],
        [0.3329, 0.4371, 0.3876],
        [0.3314, 0.4394, 0.0613]])
tensor([[1.9825, 0.4829, 0.7058],
        [1.9205, 0.6622, 1.3946],
        [1.6745, 0.5691, 2.2184]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [ ]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(A)
B = torch.tensor([[7, 8], [9, 10], [11, 12]])
print(B)

print(torch.matmul(A, B))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [ ]:
#방법1
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[7, 8], [9, 10], [11, 12]])
R = torch.matmul(A, B)

print(R + 10)
print(torch.clamp(R + 10, max=100))

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


In [ ]:
#방법2
result_add = result +10
print(result_add)

answer = torch.clamp(result, max=100)
print(answer)

tensor([[29, 32],
        [53, 60]])
tensor([[19, 22],
        [43, 50]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [ ]:
#5-1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
M = torch.tensor([
                [1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]
])

#5-2. 행렬 M의 각 열의 합계를 계산하세요
print(torch.sum(M, dim=0))

tensor([55, 60, 65, 70, 75])
