<a href="https://colab.research.google.com/github/ggmmi1/class25-1/blob/main/03_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 03. Tensor의 조작

In [ ]:
import torch

## 3-1. 인덱싱, 슬라이싱
- uumpy처럼 활용

In [ ]:
tensor = torch.tensor([[1,2],[3,4]])
print(tensor[0,1])
print(tensor[0, :])

a = torch.tensor([1,2,3,4,5])
print(a[-2:])

b = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
c = b[b > 3]
d = b[b % 2 == 0]
e = b[[0,1],[1,2]]

e



tensor(2)
tensor([1, 2])
tensor([4, 5])


tensor([2, 6])

### 3-2. Tensor의 크기, 모양 변경

In [ ]:
t = torch.rand(4,5)
print(t)

x = t.view(5,4)
print(x)

y = t.view(10,-1)
print(y)

tensor([[0.6544, 0.1603, 0.9850, 0.7239, 0.3655],
        [0.5670, 0.2928, 0.0263, 0.6655, 0.1216],
        [0.7841, 0.5320, 0.1338, 0.8303, 0.8323],
        [0.0896, 0.0501, 0.6006, 0.3115, 0.9217]])
tensor([[0.6544, 0.1603, 0.9850, 0.7239],
        [0.3655, 0.5670, 0.2928, 0.0263],
        [0.6655, 0.1216, 0.7841, 0.5320],
        [0.1338, 0.8303, 0.8323, 0.0896],
        [0.0501, 0.6006, 0.3115, 0.9217]])
tensor([[0.6544, 0.1603],
        [0.9850, 0.7239],
        [0.3655, 0.5670],
        [0.2928, 0.0263],
        [0.6655, 0.1216],
        [0.7841, 0.5320],
        [0.1338, 0.8303],
        [0.8323, 0.0896],
        [0.0501, 0.6006],
        [0.3115, 0.9217]])


### 3-3. Tensor의 숫자값 얻기

In [ ]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y)
print(y.item())

10
tensor([0.5470])
0.5470072627067566


###3-4. 차원 축소와 증가

### 3-4-1. 차원 축소
-torch.squeeze() : 크기가 1인 차원을 축소



In [ ]:
t = torch.rand(1,3,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.9601, 0.2236, 0.6979],
         [0.6971, 0.8912, 0.8256],
         [0.2861, 0.9684, 0.5899]]])
torch.Size([1, 3, 3])
tensor([[0.9601, 0.2236, 0.6979],
        [0.6971, 0.8912, 0.8256],
        [0.2861, 0.9684, 0.5899]])
torch.Size([3, 3])


### 3-4-2. 차원 증가(생성)

torch.unsqueeze(): 지정한 위치에 새로운 차원을 생성

In [ ]:
t= torch.rand(3,3,3)
print(t)
print(t.shape)

ts = torch.unsqueeze(t, 3)
print(ts)
print(ts.shape)

tensor([[[0.9818, 0.5419, 0.3793],
         [0.8295, 0.7234, 0.5217],
         [0.2283, 0.2875, 0.5813]],

        [[0.1361, 0.2900, 0.4058],
         [0.8791, 0.6506, 0.4892],
         [0.4330, 0.9867, 0.7718]],

        [[0.3784, 0.4567, 0.1206],
         [0.0692, 0.9553, 0.8842],
         [0.4316, 0.4256, 0.0302]]])
torch.Size([3, 3, 3])
tensor([[[[0.9818],
          [0.5419],
          [0.3793]],

         [[0.8295],
          [0.7234],
          [0.5217]],

         [[0.2283],
          [0.2875],
          [0.5813]]],


        [[[0.1361],
          [0.2900],
          [0.4058]],

         [[0.8791],
          [0.6506],
          [0.4892]],

         [[0.4330],
          [0.9867],
          [0.7718]]],


        [[[0.3784],
          [0.4567],
          [0.1206]],

         [[0.0692],
          [0.9553],
          [0.8842]],

         [[0.4316],
          [0.4256],
          [0.0302]]]])
torch.Size([3, 3, 3, 1])


### 3-5. Tensor간 결합

- torch.stack(): 동일한 형식의 Tensor을 새롭게 그룹화 함

- 새로운 차원 생성

In [ ]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])
z = torch.stack([x,y])
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- torch.cat() : 하나의 Tensor로 병합
- 새로운 차원 생성 x

In [ ]:
x = torch.tensor([[1,2], [3,4]])
y = torch.tensor([[5,6], [7,8]])
z = torch.cat((x,y), dim=0) #dim 지정에 따라 합쳐지는 것도 달라진다.
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 3-6 Tensor 나누기

- torch.chunk()
- Tensor를 몇 개로 나눌지 지정
- 나누어 떨어지지 않으면 마지막 조각은 크기 다를 수 있음

In [ ]:
t = torch.rand(3,3)
print(t)

#쪼개서 표현
a, b, c = torch.chunk(t, 3,dim=0) #3개로 쪼개서 출력한다.
print(a)
print(b)
print(c)

tensor([[0.8732, 0.4744, 0.6023],
        [0.0854, 0.7077, 0.7292],
        [0.5729, 0.7025, 0.2396]])
tensor([[0.8732, 0.4744, 0.6023]])
tensor([[0.0854, 0.7077, 0.7292]])
tensor([[0.5729, 0.7025, 0.2396]])


- torch.split()
 - Tensor의 크기를 기준으로 나눔


In [ ]:
t  = torch.rand(3,3)
print(t)

x = torch.split(t, 3, dim=0)
print(x)

tensor([[0.6954, 0.5911, 0.5689],
        [0.8600, 0.9703, 0.1623],
        [0.0450, 0.9874, 0.8058]])
(tensor([[0.6954, 0.5911, 0.5689],
        [0.8600, 0.9703, 0.1623],
        [0.0450, 0.9874, 0.8058]]),)


In [ ]:
t  = torch.tensor([1,2,3,4,5])
print(t)

x, y, z = torch.split(t, [2,2,1], dim=0)
print(x)
print(y)
print(z)

tensor([1, 2, 3, 4, 5])
tensor([1, 2])
tensor([3, 4])
tensor([5])
